name: Build Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-upload-artifact:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out code + LFS with cache
        uses: nschloe/action-cached-lfs-checkout@v1
        # See discussion at https://github.com/actions/checkout/issues/165
        # This is a bundling of the pattern in this comment:
        # https://github.com/actions/checkout/issues/165#issuecomment-657673315

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache-dependency-path: |
            setup.cfg
            docs/requirements.txt

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[docs]" -c "resources/constraints/constraints_py3.10.txt"

      - name: Build Docs
        uses: aganders3/headless-gui@v1
        env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
        with:
          run: make docs

      # TODO: enable when the link check passes
      # - name: LinkCheck
      #  run: make linkcheck-files

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build

